CREATE DATABASE M_InLock;

USE M_InLock;

CREATE TABLE Usuarios (
	UsuarioId		INT PRIMARY KEY IDENTITY NOT NULL
	,Email			VARCHAR (255) UNIQUE NOT NULL
	,Senha			VARCHAR (255) NOT NULL
	,Permissao		VARCHAR (255) NOT NULL
);

CREATE TABLE Estudios (
	EstudioId		INT PRIMARY KEY IDENTITY NOT NULL
	,NomeEstudio	VARCHAR (255) NOT NULL UNIQUE
	,PaisOrigem		VARCHAR (255) NOT NULL
	,DataCriacao	DATE NOT NULL
	,UsuarioId		INT FOREIGN KEY REFERENCES Usuarios (UsuarioId)
);

CREATE TABLE Jogos (
	JogoId			INT PRIMARY KEY IDENTITY NOT NULL
	,NomeJogo		VARCHAR (255) NOT NULL UNIQUE
	,Descricao		TEXT NOT NULL
	,DataLancamento	DATE NOT NULL
	,Valor			FLOAT NOT NULL
	,EstudioId		INT FOREIGN KEY REFERENCES Estudios (EstudioId)
);


